-- DROP DATABASE IF EXISTS BAMAZON_DB;
-- CREATE DATABASE BAMAZON_DB;
-- 
USE BAMAZON_DB;
-- 
-- CREATE TABLE PRODUCTS (
--   ITEM_ID INT NOT NULL,
--   PRODUCT_NAME VARCHAR(100) NULL,
--   DEPARTMENT_NAME VARCHAR(100) NULL,
--   PRICE DECIMAL(10,2) NULL,
--   STOCK_QT INTEGER (11) NULL,
--   PRIMARY KEY (ITEM_ID)
-- );
-- 
SELECT * FROM PRODUCTS;
-- 
-- INSERT INTO PRODUCTS (ITEM_ID,PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QT)
-- VALUES ("01","TIDE PODS 3 IN 1", "HEALTH&HOUSEHOLD", "18.99","100");

-- INSERT INTO PRODUCTS (ITEM_ID,PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QT)
-- VALUES ("2","ECHO DOT", "ELECTRONICS", "49.99","86");

-- INSERT INTO PRODUCTS (ITEM_ID,PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QT)
-- VALUES ("03","JENGA CLASSIC GAME", "TOYS&GAMES", "10.27","10");

-- INSERT INTO PRODUCTS (ITEM_ID,PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QT)
-- VALUES ("04","SEA FOAM MOTO TREATMENT", "AUTOMOTIVE", "11.95","50");

